baseURL = 'https://willgardner.uk'
languageCode = 'en-gb'
title = ''

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[params]
title = "Will Gardner"
author = "Will Gardner"
description = "Software Engineer, Sailor"
profilePicture = "images/profile.jpeg"
postSectionName = "blog"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/chippiewill/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/Chippiewill"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
